package com.nielsen.confirmit.webservices.authoring;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.4
 * 2019-11-07T17:53:20.576+05:30
 * Generated source version: 3.3.4
 *
 */
@WebService(targetNamespace = "http://firmglobal.com/Confirmit/webservices/", name = "AuthoringSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface AuthoringSoap {

    @WebMethod(operationName = "GetCustomProjectInfoField", action = "http://firmglobal.com/Confirmit/webservices/GetCustomProjectInfoField")
    @RequestWrapper(localName = "GetCustomProjectInfoField", targetNamespace = "http://firmglobal.com/Confirmit/webservices/", className = "com.nielsen.confirmit.webservices.authoring.GetCustomProjectInfoField")
    @ResponseWrapper(localName = "GetCustomProjectInfoFieldResponse", targetNamespace = "http://firmglobal.com/Confirmit/webservices/", className = "com.nielsen.confirmit.webservices.authoring.GetCustomProjectInfoFieldResponse")
    @WebResult(name = "GetCustomProjectInfoFieldResult", targetNamespace = "http://firmglobal.com/Confirmit/webservices/")
    public java.lang.String getCustomProjectInfoField(

        @WebParam(name = "key", targetNamespace = "http://firmglobal.com/Confirmit/webservices/")
        java.lang.String key,
        @WebParam(name = "projectId", targetNamespace = "http://firmglobal.com/Confirmit/webservices/")
        java.lang.String projectId,
        @WebParam(name = "fieldId", targetNamespace = "http://firmglobal.com/Confirmit/webservices/")
        java.lang.String fieldId
    );

    @WebMethod(operationName = "ExportTranslation", action = "http://firmglobal.com/Confirmit/webservices/ExportTranslation")
    @RequestWrapper(localName = "ExportTranslation", targetNamespace = "http://firmglobal.com/Confirmit/webservices/", className = "com.nielsen.confirmit.webservices.authoring.ExportTranslation")
    @ResponseWrapper(localName = "ExportTranslationResponse", targetNamespace = "http://firmglobal.com/Confirmit/webservices/", className = "com.nielsen.confirmit.webservices.authoring.ExportTranslationResponse")
    @WebResult(name = "ExportTranslationResult", targetNamespace = "http://firmglobal.com/Confirmit/webservices/")
    public java.lang.String exportTranslation(

        @WebParam(name = "key", targetNamespace = "http://firmglobal.com/Confirmit/webservices/")
        java.lang.String key,
        @WebParam(name = "projectId", targetNamespace = "http://firmglobal.com/Confirmit/webservices/")
        java.lang.String projectId,
        @WebParam(name = "targetLanguage", targetNamespace = "http://firmglobal.com/Confirmit/webservices/")
        int targetLanguage,
        @WebParam(name = "baseLanguage", targetNamespace = "http://firmglobal.com/Confirmit/webservices/")
        int baseLanguage,
        @WebParam(name = "useFallbackLanguage", targetNamespace = "http://firmglobal.com/Confirmit/webservices/")
        boolean useFallbackLanguage,
        @WebParam(name = "fallbackLanguage", targetNamespace = "http://firmglobal.com/Confirmit/webservices/")
        int fallbackLanguage
    );

    @WebMethod(operationName = "GetNodes", action = "http://firmglobal.com/Confirmit/webservices/GetNodes")
    @RequestWrapper(localName = "GetNodes", targetNamespace = "http://firmglobal.com/Confirmit/webservices/", className = "com.nielsen.confirmit.webservices.authoring.GetNodes")
    @ResponseWrapper(localName = "GetNodesResponse", targetNamespace = "http://firmglobal.com/Confirmit/webservices/", className = "com.nielsen.confirmit.webservices.authoring.GetNodesResponse")
    @WebResult(name = "GetNodesResult", targetNamespace = "http://firmglobal.com/Confirmit/webservices/")
    public com.nielsen.confirmit.webservices.authoring.SurveySchema getNodes(

        @WebParam(name = "key", targetNamespace = "http://firmglobal.com/Confirmit/webservices/")
        java.lang.String key,
        @WebParam(name = "projectId", targetNamespace = "http://firmglobal.com/Confirmit/webservices/")
        java.lang.String projectId,
        @WebParam(name = "parent", targetNamespace = "http://firmglobal.com/Confirmit/webservices/")
        com.nielsen.confirmit.webservices.authoring.Node parent,
        @WebParam(name = "poetReadFilter", targetNamespace = "http://firmglobal.com/Confirmit/webservices/")
        com.nielsen.confirmit.webservices.authoring.PoetReadFilter poetReadFilter
    );

    @WebMethod(operationName = "GetForm", action = "http://firmglobal.com/Confirmit/webservices/GetForm")
    @RequestWrapper(localName = "GetForm", targetNamespace = "http://firmglobal.com/Confirmit/webservices/", className = "com.nielsen.confirmit.webservices.authoring.GetForm")
    @ResponseWrapper(localName = "GetFormResponse", targetNamespace = "http://firmglobal.com/Confirmit/webservices/", className = "com.nielsen.confirmit.webservices.authoring.GetFormResponse")
    @WebResult(name = "GetFormResult", targetNamespace = "http://firmglobal.com/Confirmit/webservices/")
    public com.nielsen.confirmit.webservices.authoring.SurveySchema getForm(

        @WebParam(name = "key", targetNamespace = "http://firmglobal.com/Confirmit/webservices/")
        java.lang.String key,
        @WebParam(name = "projectId", targetNamespace = "http://firmglobal.com/Confirmit/webservices/")
        java.lang.String projectId,
        @WebParam(name = "form", targetNamespace = "http://firmglobal.com/Confirmit/webservices/")
        com.nielsen.confirmit.webservices.authoring.FormBase form,
        @WebParam(name = "readFilterSimple", targetNamespace = "http://firmglobal.com/Confirmit/webservices/")
        com.nielsen.confirmit.webservices.authoring.ReadFilterSimple readFilterSimple,
        @WebParam(name = "schemaSource", targetNamespace = "http://firmglobal.com/Confirmit/webservices/")
        com.nielsen.confirmit.webservices.authoring.SchemaSourceType schemaSource
    );

    @WebMethod(operationName = "GetConditionBranch", action = "http://firmglobal.com/Confirmit/webservices/GetConditionBranch")
    @RequestWrapper(localName = "GetConditionBranch", targetNamespace = "http://firmglobal.com/Confirmit/webservices/", className = "com.nielsen.confirmit.webservices.authoring.GetConditionBranch")
    @ResponseWrapper(localName = "GetConditionBranchResponse", targetNamespace = "http://firmglobal.com/Confirmit/webservices/", className = "com.nielsen.confirmit.webservices.authoring.GetConditionBranchResponse")
    @WebResult(name = "GetConditionBranchResult", targetNamespace = "http://firmglobal.com/Confirmit/webservices/")
    public com.nielsen.confirmit.webservices.authoring.SurveySchema getConditionBranch(

        @WebParam(name = "key", targetNamespace = "http://firmglobal.com/Confirmit/webservices/")
        java.lang.String key,
        @WebParam(name = "projectId", targetNamespace = "http://firmglobal.com/Confirmit/webservices/")
        java.lang.String projectId,
        @WebParam(name = "parent", targetNamespace = "http://firmglobal.com/Confirmit/webservices/")
        com.nielsen.confirmit.webservices.authoring.Condition parent,
        @WebParam(name = "poetReadFilter", targetNamespace = "http://firmglobal.com/Confirmit/webservices/")
        com.nielsen.confirmit.webservices.authoring.PoetReadFilter poetReadFilter,
        @WebParam(name = "trueBranch", targetNamespace = "http://firmglobal.com/Confirmit/webservices/")
        boolean trueBranch
    );

    @WebMethod(operationName = "GetNode", action = "http://firmglobal.com/Confirmit/webservices/GetNode")
    @RequestWrapper(localName = "GetNode", targetNamespace = "http://firmglobal.com/Confirmit/webservices/", className = "com.nielsen.confirmit.webservices.authoring.GetNode")
    @ResponseWrapper(localName = "GetNodeResponse", targetNamespace = "http://firmglobal.com/Confirmit/webservices/", className = "com.nielsen.confirmit.webservices.authoring.GetNodeResponse")
    @WebResult(name = "GetNodeResult", targetNamespace = "http://firmglobal.com/Confirmit/webservices/")
    public com.nielsen.confirmit.webservices.authoring.SurveySchema getNode(

        @WebParam(name = "key", targetNamespace = "http://firmglobal.com/Confirmit/webservices/")
        java.lang.String key,
        @WebParam(name = "projectId", targetNamespace = "http://firmglobal.com/Confirmit/webservices/")
        java.lang.String projectId,
        @WebParam(name = "node", targetNamespace = "http://firmglobal.com/Confirmit/webservices/")
        com.nielsen.confirmit.webservices.authoring.Node node,
        @WebParam(name = "poetReadFilter", targetNamespace = "http://firmglobal.com/Confirmit/webservices/")
        com.nielsen.confirmit.webservices.authoring.PoetReadFilter poetReadFilter
    );

    @WebMethod(operationName = "ProjectExists", action = "http://firmglobal.com/Confirmit/webservices/ProjectExists")
    @RequestWrapper(localName = "ProjectExists", targetNamespace = "http://firmglobal.com/Confirmit/webservices/", className = "com.nielsen.confirmit.webservices.authoring.ProjectExists")
    @ResponseWrapper(localName = "ProjectExistsResponse", targetNamespace = "http://firmglobal.com/Confirmit/webservices/", className = "com.nielsen.confirmit.webservices.authoring.ProjectExistsResponse")
    @WebResult(name = "ProjectExistsResult", targetNamespace = "http://firmglobal.com/Confirmit/webservices/")
    public boolean projectExists(

        @WebParam(name = "key", targetNamespace = "http://firmglobal.com/Confirmit/webservices/")
        java.lang.String key,
        @WebParam(name = "projectId", targetNamespace = "http://firmglobal.com/Confirmit/webservices/")
        java.lang.String projectId
    );

    @WebMethod(operationName = "GetProjectListByProjectName", action = "http://firmglobal.com/Confirmit/webservices/GetProjectListByProjectName")
    @RequestWrapper(localName = "GetProjectListByProjectName", targetNamespace = "http://firmglobal.com/Confirmit/webservices/", className = "com.nielsen.confirmit.webservices.authoring.GetProjectListByProjectName")
    @ResponseWrapper(localName = "GetProjectListByProjectNameResponse", targetNamespace = "http://firmglobal.com/Confirmit/webservices/", className = "com.nielsen.confirmit.webservices.authoring.GetProjectListByProjectNameResponse")
    @WebResult(name = "GetProjectListByProjectNameResult", targetNamespace = "http://firmglobal.com/Confirmit/webservices/")
    public com.nielsen.confirmit.webservices.authoring.ProjectListResultSet getProjectListByProjectName(

        @WebParam(name = "key", targetNamespace = "http://firmglobal.com/Confirmit/webservices/")
        java.lang.String key,
        @WebParam(name = "projectType", targetNamespace = "http://firmglobal.com/Confirmit/webservices/")
        com.nielsen.confirmit.webservices.authoring.ProjectType projectType,
        @WebParam(name = "allProjects", targetNamespace = "http://firmglobal.com/Confirmit/webservices/")
        boolean allProjects,
        @WebParam(name = "token", targetNamespace = "http://firmglobal.com/Confirmit/webservices/")
        com.nielsen.confirmit.webservices.authoring.ProjectListToken token,
        @WebParam(name = "topN", targetNamespace = "http://firmglobal.com/Confirmit/webservices/")
        int topN,
        @WebParam(name = "projectName", targetNamespace = "http://firmglobal.com/Confirmit/webservices/")
        java.lang.String projectName
    );

    @WebMethod(operationName = "DeleteQuestionnaire", action = "http://firmglobal.com/Confirmit/webservices/DeleteQuestionnaire")
    @RequestWrapper(localName = "DeleteQuestionnaire", targetNamespace = "http://firmglobal.com/Confirmit/webservices/", className = "com.nielsen.confirmit.webservices.authoring.DeleteQuestionnaire")
    @ResponseWrapper(localName = "DeleteQuestionnaireResponse", targetNamespace = "http://firmglobal.com/Confirmit/webservices/", className = "com.nielsen.confirmit.webservices.authoring.DeleteQuestionnaireResponse")
    public void deleteQuestionnaire(

        @WebParam(name = "key", targetNamespace = "http://firmglobal.com/Confirmit/webservices/")
        java.lang.String key,
        @WebParam(name = "projectId", targetNamespace = "http://firmglobal.com/Confirmit/webservices/")
        java.lang.String projectId
    );

    @WebMethod(operationName = "ImportTranslation", action = "http://firmglobal.com/Confirmit/webservices/ImportTranslation")
    @RequestWrapper(localName = "ImportTranslation", targetNamespace = "http://firmglobal.com/Confirmit/webservices/", className = "com.nielsen.confirmit.webservices.authoring.ImportTranslation")
    @ResponseWrapper(localName = "ImportTranslationResponse", targetNamespace = "http://firmglobal.com/Confirmit/webservices/", className = "com.nielsen.confirmit.webservices.authoring.ImportTranslationResponse")
    public void importTranslation(

        @WebParam(name = "key", targetNamespace = "http://firmglobal.com/Confirmit/webservices/")
        java.lang.String key,
        @WebParam(name = "projectId", targetNamespace = "http://firmglobal.com/Confirmit/webservices/")
        java.lang.String projectId,
        @WebParam(name = "translationXml", targetNamespace = "http://firmglobal.com/Confirmit/webservices/")
        java.lang.String translationXml
    );

    @WebMethod(operationName = "GetProjectListByKeywords", action = "http://firmglobal.com/Confirmit/webservices/GetProjectListByKeywords")
    @RequestWrapper(localName = "GetProjectListByKeywords", targetNamespace = "http://firmglobal.com/Confirmit/webservices/", className = "com.nielsen.confirmit.webservices.authoring.GetProjectListByKeywords")
    @ResponseWrapper(localName = "GetProjectListByKeywordsResponse", targetNamespace = "http://firmglobal.com/Confirmit/webservices/", className = "com.nielsen.confirmit.webservices.authoring.GetProjectListByKeywordsResponse")
    @WebResult(name = "GetProjectListByKeywordsResult", targetNamespace = "http://firmglobal.com/Confirmit/webservices/")
    public com.nielsen.confirmit.webservices.authoring.ProjectListResultSet getProjectListByKeywords(

        @WebParam(name = "key", targetNamespace = "http://firmglobal.com/Confirmit/webservices/")
        java.lang.String key,
        @WebParam(name = "projectType", targetNamespace = "http://firmglobal.com/Confirmit/webservices/")
        com.nielsen.confirmit.webservices.authoring.ProjectType projectType,
        @WebParam(name = "allProjects", targetNamespace = "http://firmglobal.com/Confirmit/webservices/")
        boolean allProjects,
        @WebParam(name = "token", targetNamespace = "http://firmglobal.com/Confirmit/webservices/")
        com.nielsen.confirmit.webservices.authoring.ProjectListToken token,
        @WebParam(name = "topN", targetNamespace = "http://firmglobal.com/Confirmit/webservices/")
        int topN,
        @WebParam(name = "keywords", targetNamespace = "http://firmglobal.com/Confirmit/webservices/")
        com.nielsen.confirmit.webservices.authoring.ArrayOfString1 keywords
    );

    @WebMethod(operationName = "GetPredefinedLists", action = "http://firmglobal.com/Confirmit/webservices/GetPredefinedLists")
    @RequestWrapper(localName = "GetPredefinedLists", targetNamespace = "http://firmglobal.com/Confirmit/webservices/", className = "com.nielsen.confirmit.webservices.authoring.GetPredefinedLists")
    @ResponseWrapper(localName = "GetPredefinedListsResponse", targetNamespace = "http://firmglobal.com/Confirmit/webservices/", className = "com.nielsen.confirmit.webservices.authoring.GetPredefinedListsResponse")
    @WebResult(name = "GetPredefinedListsResult", targetNamespace = "http://firmglobal.com/Confirmit/webservices/")
    public com.nielsen.confirmit.webservices.authoring.SurveySchema getPredefinedLists(

        @WebParam(name = "key", targetNamespace = "http://firmglobal.com/Confirmit/webservices/")
        java.lang.String key,
        @WebParam(name = "projectId", targetNamespace = "http://firmglobal.com/Confirmit/webservices/")
        java.lang.String projectId,
        @WebParam(name = "readFilterSimple", targetNamespace = "http://firmglobal.com/Confirmit/webservices/")
        com.nielsen.confirmit.webservices.authoring.ReadFilterSimple readFilterSimple
    );

    @WebMethod(operationName = "GetSurveyStatus", action = "http://firmglobal.com/Confirmit/webservices/GetSurveyStatus")
    @RequestWrapper(localName = "GetSurveyStatus", targetNamespace = "http://firmglobal.com/Confirmit/webservices/", className = "com.nielsen.confirmit.webservices.authoring.GetSurveyStatus")
    @ResponseWrapper(localName = "GetSurveyStatusResponse", targetNamespace = "http://firmglobal.com/Confirmit/webservices/", className = "com.nielsen.confirmit.webservices.authoring.GetSurveyStatusResponse")
    @WebResult(name = "GetSurveyStatusResult", targetNamespace = "http://firmglobal.com/Confirmit/webservices/")
    public com.nielsen.confirmit.webservices.authoring.SurveyStatusType getSurveyStatus(

        @WebParam(name = "key", targetNamespace = "http://firmglobal.com/Confirmit/webservices/")
        java.lang.String key,
        @WebParam(name = "projectId", targetNamespace = "http://firmglobal.com/Confirmit/webservices/")
        java.lang.String projectId
    );

    @WebMethod(operationName = "SetSurveyStatus", action = "http://firmglobal.com/Confirmit/webservices/SetSurveyStatus")
    @RequestWrapper(localName = "SetSurveyStatus", targetNamespace = "http://firmglobal.com/Confirmit/webservices/", className = "com.nielsen.confirmit.webservices.authoring.SetSurveyStatus")
    @ResponseWrapper(localName = "SetSurveyStatusResponse", targetNamespace = "http://firmglobal.com/Confirmit/webservices/", className = "com.nielsen.confirmit.webservices.authoring.SetSurveyStatusResponse")
    public void setSurveyStatus(

        @WebParam(name = "key", targetNamespace = "http://firmglobal.com/Confirmit/webservices/")
        java.lang.String key,
        @WebParam(name = "projectId", targetNamespace = "http://firmglobal.com/Confirmit/webservices/")
        java.lang.String projectId,
        @WebParam(name = "status", targetNamespace = "http://firmglobal.com/Confirmit/webservices/")
        com.nielsen.confirmit.webservices.authoring.SurveyStatusType status
    );

    @WebMethod(operationName = "DeleteProject", action = "http://firmglobal.com/Confirmit/webservices/DeleteProject")
    @RequestWrapper(localName = "DeleteProject", targetNamespace = "http://firmglobal.com/Confirmit/webservices/", className = "com.nielsen.confirmit.webservices.authoring.DeleteProject")
    @ResponseWrapper(localName = "DeleteProjectResponse", targetNamespace = "http://firmglobal.com/Confirmit/webservices/", className = "com.nielsen.confirmit.webservices.authoring.DeleteProjectResponse")
    public void deleteProject(

        @WebParam(name = "key", targetNamespace = "http://firmglobal.com/Confirmit/webservices/")
        java.lang.String key,
        @WebParam(name = "projectId", targetNamespace = "http://firmglobal.com/Confirmit/webservices/")
        java.lang.String projectId
    );

    @WebMethod(operationName = "GetPredefinedList", action = "http://firmglobal.com/Confirmit/webservices/GetPredefinedList")
    @RequestWrapper(localName = "GetPredefinedList", targetNamespace = "http://firmglobal.com/Confirmit/webservices/", className = "com.nielsen.confirmit.webservices.authoring.GetPredefinedList")
    @ResponseWrapper(localName = "GetPredefinedListResponse", targetNamespace = "http://firmglobal.com/Confirmit/webservices/", className = "com.nielsen.confirmit.webservices.authoring.GetPredefinedListResponse")
    @WebResult(name = "GetPredefinedListResult", targetNamespace = "http://firmglobal.com/Confirmit/webservices/")
    public com.nielsen.confirmit.webservices.authoring.SurveySchema getPredefinedList(

        @WebParam(name = "key", targetNamespace = "http://firmglobal.com/Confirmit/webservices/")
        java.lang.String key,
        @WebParam(name = "projectId", targetNamespace = "http://firmglobal.com/Confirmit/webservices/")
        java.lang.String projectId,
        @WebParam(name = "name", targetNamespace = "http://firmglobal.com/Confirmit/webservices/")
        java.lang.String name,
        @WebParam(name = "readFilterSimple", targetNamespace = "http://firmglobal.com/Confirmit/webservices/")
        com.nielsen.confirmit.webservices.authoring.ReadFilterSimple readFilterSimple
    );

    @WebMethod(operationName = "GetFormByName", action = "http://firmglobal.com/Confirmit/webservices/GetFormByName")
    @RequestWrapper(localName = "GetFormByName", targetNamespace = "http://firmglobal.com/Confirmit/webservices/", className = "com.nielsen.confirmit.webservices.authoring.GetFormByName")
    @ResponseWrapper(localName = "GetFormByNameResponse", targetNamespace = "http://firmglobal.com/Confirmit/webservices/", className = "com.nielsen.confirmit.webservices.authoring.GetFormByNameResponse")
    @WebResult(name = "GetFormByNameResult", targetNamespace = "http://firmglobal.com/Confirmit/webservices/")
    public com.nielsen.confirmit.webservices.authoring.SurveySchema getFormByName(

        @WebParam(name = "key", targetNamespace = "http://firmglobal.com/Confirmit/webservices/")
        java.lang.String key,
        @WebParam(name = "projectId", targetNamespace = "http://firmglobal.com/Confirmit/webservices/")
        java.lang.String projectId,
        @WebParam(name = "name", targetNamespace = "http://firmglobal.com/Confirmit/webservices/")
        java.lang.String name,
        @WebParam(name = "readFilterSimple", targetNamespace = "http://firmglobal.com/Confirmit/webservices/")
        com.nielsen.confirmit.webservices.authoring.ReadFilterSimple readFilterSimple,
        @WebParam(name = "schemaSource", targetNamespace = "http://firmglobal.com/Confirmit/webservices/")
        com.nielsen.confirmit.webservices.authoring.SchemaSourceType schemaSource
    );

    @WebMethod(operationName = "DuplicateProject", action = "http://firmglobal.com/Confirmit/webservices/DuplicateProject")
    @RequestWrapper(localName = "DuplicateProject", targetNamespace = "http://firmglobal.com/Confirmit/webservices/", className = "com.nielsen.confirmit.webservices.authoring.DuplicateProject")
    @ResponseWrapper(localName = "DuplicateProjectResponse", targetNamespace = "http://firmglobal.com/Confirmit/webservices/", className = "com.nielsen.confirmit.webservices.authoring.DuplicateProjectResponse")
    @WebResult(name = "DuplicateProjectResult", targetNamespace = "http://firmglobal.com/Confirmit/webservices/")
    public java.lang.String duplicateProject(

        @WebParam(name = "key", targetNamespace = "http://firmglobal.com/Confirmit/webservices/")
        java.lang.String key,
        @WebParam(name = "projectId", targetNamespace = "http://firmglobal.com/Confirmit/webservices/")
        java.lang.String projectId,
        @WebParam(name = "newProjectName", targetNamespace = "http://firmglobal.com/Confirmit/webservices/")
        java.lang.String newProjectName
    );

    @WebMethod(operationName = "GetProjectListByCreator", action = "http://firmglobal.com/Confirmit/webservices/GetProjectListByCreator")
    @RequestWrapper(localName = "GetProjectListByCreator", targetNamespace = "http://firmglobal.com/Confirmit/webservices/", className = "com.nielsen.confirmit.webservices.authoring.GetProjectListByCreator")
    @ResponseWrapper(localName = "GetProjectListByCreatorResponse", targetNamespace = "http://firmglobal.com/Confirmit/webservices/", className = "com.nielsen.confirmit.webservices.authoring.GetProjectListByCreatorResponse")
    @WebResult(name = "GetProjectListByCreatorResult", targetNamespace = "http://firmglobal.com/Confirmit/webservices/")
    public com.nielsen.confirmit.webservices.authoring.ProjectListResultSet getProjectListByCreator(

        @WebParam(name = "key", targetNamespace = "http://firmglobal.com/Confirmit/webservices/")
        java.lang.String key,
        @WebParam(name = "projectType", targetNamespace = "http://firmglobal.com/Confirmit/webservices/")
        com.nielsen.confirmit.webservices.authoring.ProjectType projectType,
        @WebParam(name = "allProjects", targetNamespace = "http://firmglobal.com/Confirmit/webservices/")
        boolean allProjects,
        @WebParam(name = "token", targetNamespace = "http://firmglobal.com/Confirmit/webservices/")
        com.nielsen.confirmit.webservices.authoring.ProjectListToken token,
        @WebParam(name = "topN", targetNamespace = "http://firmglobal.com/Confirmit/webservices/")
        int topN,
        @WebParam(name = "createdByLastName", targetNamespace = "http://firmglobal.com/Confirmit/webservices/")
        java.lang.String createdByLastName
    );

    @WebMethod(operationName = "DeleteRouting", action = "http://firmglobal.com/Confirmit/webservices/DeleteRouting")
    @RequestWrapper(localName = "DeleteRouting", targetNamespace = "http://firmglobal.com/Confirmit/webservices/", className = "com.nielsen.confirmit.webservices.authoring.DeleteRouting")
    @ResponseWrapper(localName = "DeleteRoutingResponse", targetNamespace = "http://firmglobal.com/Confirmit/webservices/", className = "com.nielsen.confirmit.webservices.authoring.DeleteRoutingResponse")
    public void deleteRouting(

        @WebParam(name = "key", targetNamespace = "http://firmglobal.com/Confirmit/webservices/")
        java.lang.String key,
        @WebParam(name = "projectId", targetNamespace = "http://firmglobal.com/Confirmit/webservices/")
        java.lang.String projectId
    );

    @WebMethod(operationName = "GetFormsInLoop", action = "http://firmglobal.com/Confirmit/webservices/GetFormsInLoop")
    @RequestWrapper(localName = "GetFormsInLoop", targetNamespace = "http://firmglobal.com/Confirmit/webservices/", className = "com.nielsen.confirmit.webservices.authoring.GetFormsInLoop")
    @ResponseWrapper(localName = "GetFormsInLoopResponse", targetNamespace = "http://firmglobal.com/Confirmit/webservices/", className = "com.nielsen.confirmit.webservices.authoring.GetFormsInLoopResponse")
    @WebResult(name = "GetFormsInLoopResult", targetNamespace = "http://firmglobal.com/Confirmit/webservices/")
    public com.nielsen.confirmit.webservices.authoring.SurveySchema getFormsInLoop(

        @WebParam(name = "key", targetNamespace = "http://firmglobal.com/Confirmit/webservices/")
        java.lang.String key,
        @WebParam(name = "projectId", targetNamespace = "http://firmglobal.com/Confirmit/webservices/")
        java.lang.String projectId,
        @WebParam(name = "parent", targetNamespace = "http://firmglobal.com/Confirmit/webservices/")
        com.nielsen.confirmit.webservices.authoring.Node parent,
        @WebParam(name = "readFilter", targetNamespace = "http://firmglobal.com/Confirmit/webservices/")
        com.nielsen.confirmit.webservices.authoring.ReadFilter readFilter,
        @WebParam(name = "schemaSource", targetNamespace = "http://firmglobal.com/Confirmit/webservices/")
        com.nielsen.confirmit.webservices.authoring.SchemaSourceType schemaSource
    );

    @WebMethod(operationName = "GetExternalAnswers", action = "http://firmglobal.com/Confirmit/webservices/GetExternalAnswers")
    @RequestWrapper(localName = "GetExternalAnswers", targetNamespace = "http://firmglobal.com/Confirmit/webservices/", className = "com.nielsen.confirmit.webservices.authoring.GetExternalAnswers")
    @ResponseWrapper(localName = "GetExternalAnswersResponse", targetNamespace = "http://firmglobal.com/Confirmit/webservices/", className = "com.nielsen.confirmit.webservices.authoring.GetExternalAnswersResponse")
    @WebResult(name = "GetExternalAnswersResult", targetNamespace = "http://firmglobal.com/Confirmit/webservices/")
    public com.nielsen.confirmit.webservices.authoring.ArrayOfAnswerBase getExternalAnswers(

        @WebParam(name = "key", targetNamespace = "http://firmglobal.com/Confirmit/webservices/")
        java.lang.String key,
        @WebParam(name = "projectId", targetNamespace = "http://firmglobal.com/Confirmit/webservices/")
        java.lang.String projectId,
        @WebParam(name = "name", targetNamespace = "http://firmglobal.com/Confirmit/webservices/")
        java.lang.String name
    );

    @WebMethod(operationName = "GetProjectInfo", action = "http://firmglobal.com/Confirmit/webservices/GetProjectInfo")
    @RequestWrapper(localName = "GetProjectInfo", targetNamespace = "http://firmglobal.com/Confirmit/webservices/", className = "com.nielsen.confirmit.webservices.authoring.GetProjectInfo")
    @ResponseWrapper(localName = "GetProjectInfoResponse", targetNamespace = "http://firmglobal.com/Confirmit/webservices/", className = "com.nielsen.confirmit.webservices.authoring.GetProjectInfoResponse")
    @WebResult(name = "GetProjectInfoResult", targetNamespace = "http://firmglobal.com/Confirmit/webservices/")
    public com.nielsen.confirmit.webservices.authoring.SurveySchema getProjectInfo(

        @WebParam(name = "key", targetNamespace = "http://firmglobal.com/Confirmit/webservices/")
        java.lang.String key,
        @WebParam(name = "projectId", targetNamespace = "http://firmglobal.com/Confirmit/webservices/")
        java.lang.String projectId
    );

    @WebMethod(operationName = "GetFilteredQuestionnaire", action = "http://firmglobal.com/Confirmit/webservices/GetFilteredQuestionnaire")
    @RequestWrapper(localName = "GetFilteredQuestionnaire", targetNamespace = "http://firmglobal.com/Confirmit/webservices/", className = "com.nielsen.confirmit.webservices.authoring.GetFilteredQuestionnaire")
    @ResponseWrapper(localName = "GetFilteredQuestionnaireResponse", targetNamespace = "http://firmglobal.com/Confirmit/webservices/", className = "com.nielsen.confirmit.webservices.authoring.GetFilteredQuestionnaireResponse")
    @WebResult(name = "GetFilteredQuestionnaireResult", targetNamespace = "http://firmglobal.com/Confirmit/webservices/")
    public com.nielsen.confirmit.webservices.authoring.SurveySchema getFilteredQuestionnaire(

        @WebParam(name = "key", targetNamespace = "http://firmglobal.com/Confirmit/webservices/")
        java.lang.String key,
        @WebParam(name = "projectId", targetNamespace = "http://firmglobal.com/Confirmit/webservices/")
        java.lang.String projectId,
        @WebParam(name = "projectSpecific", targetNamespace = "http://firmglobal.com/Confirmit/webservices/")
        boolean projectSpecific,
        @WebParam(name = "filter", targetNamespace = "http://firmglobal.com/Confirmit/webservices/")
        com.nielsen.confirmit.webservices.authoring.PoetReadFilter filter
    );

    @WebMethod(operationName = "GetQuota", action = "http://firmglobal.com/Confirmit/webservices/GetQuota")
    @RequestWrapper(localName = "GetQuota", targetNamespace = "http://firmglobal.com/Confirmit/webservices/", className = "com.nielsen.confirmit.webservices.authoring.GetQuota")
    @ResponseWrapper(localName = "GetQuotaResponse", targetNamespace = "http://firmglobal.com/Confirmit/webservices/", className = "com.nielsen.confirmit.webservices.authoring.GetQuotaResponse")
    @WebResult(name = "GetQuotaResult", targetNamespace = "http://firmglobal.com/Confirmit/webservices/")
    public com.nielsen.confirmit.webservices.authoring.SurveySchema getQuota(

        @WebParam(name = "key", targetNamespace = "http://firmglobal.com/Confirmit/webservices/")
        java.lang.String key,
        @WebParam(name = "projectId", targetNamespace = "http://firmglobal.com/Confirmit/webservices/")
        java.lang.String projectId,
        @WebParam(name = "name", targetNamespace = "http://firmglobal.com/Confirmit/webservices/")
        java.lang.String name,
        @WebParam(name = "projectSpecific", targetNamespace = "http://firmglobal.com/Confirmit/webservices/")
        boolean projectSpecific
    );

    @WebMethod(operationName = "AddProjectFromTripleS", action = "http://firmglobal.com/Confirmit/webservices/AddProjectFromTripleS")
    @RequestWrapper(localName = "AddProjectFromTripleS", targetNamespace = "http://firmglobal.com/Confirmit/webservices/", className = "com.nielsen.confirmit.webservices.authoring.AddProjectFromTripleS")
    @ResponseWrapper(localName = "AddProjectFromTripleSResponse", targetNamespace = "http://firmglobal.com/Confirmit/webservices/", className = "com.nielsen.confirmit.webservices.authoring.AddProjectFromTripleSResponse")
    @WebResult(name = "AddProjectFromTripleSResult", targetNamespace = "http://firmglobal.com/Confirmit/webservices/")
    public java.lang.String addProjectFromTripleS(

        @WebParam(name = "key", targetNamespace = "http://firmglobal.com/Confirmit/webservices/")
        java.lang.String key,
        @WebParam(name = "sss", targetNamespace = "http://firmglobal.com/Confirmit/webservices/")
        com.nielsen.confirmit.webservices.authoring.SssSchema sss,
        @WebParam(name = "language", targetNamespace = "http://firmglobal.com/Confirmit/webservices/")
        int language
    );

    @WebMethod(operationName = "GetProjectListByCreatedDate", action = "http://firmglobal.com/Confirmit/webservices/GetProjectListByCreatedDate")
    @RequestWrapper(localName = "GetProjectListByCreatedDate", targetNamespace = "http://firmglobal.com/Confirmit/webservices/", className = "com.nielsen.confirmit.webservices.authoring.GetProjectListByCreatedDate")
    @ResponseWrapper(localName = "GetProjectListByCreatedDateResponse", targetNamespace = "http://firmglobal.com/Confirmit/webservices/", className = "com.nielsen.confirmit.webservices.authoring.GetProjectListByCreatedDateResponse")
    @WebResult(name = "GetProjectListByCreatedDateResult", targetNamespace = "http://firmglobal.com/Confirmit/webservices/")
    public com.nielsen.confirmit.webservices.authoring.ProjectListResultSet getProjectListByCreatedDate(

        @WebParam(name = "key", targetNamespace = "http://firmglobal.com/Confirmit/webservices/")
        java.lang.String key,
        @WebParam(name = "projectType", targetNamespace = "http://firmglobal.com/Confirmit/webservices/")
        com.nielsen.confirmit.webservices.authoring.ProjectType projectType,
        @WebParam(name = "allProjects", targetNamespace = "http://firmglobal.com/Confirmit/webservices/")
        boolean allProjects,
        @WebParam(name = "token", targetNamespace = "http://firmglobal.com/Confirmit/webservices/")
        com.nielsen.confirmit.webservices.authoring.ProjectListToken token,
        @WebParam(name = "topN", targetNamespace = "http://firmglobal.com/Confirmit/webservices/")
        int topN,
        @WebParam(name = "createdFrom", targetNamespace = "http://firmglobal.com/Confirmit/webservices/")
        javax.xml.datatype.XMLGregorianCalendar createdFrom,
        @WebParam(name = "createdTo", targetNamespace = "http://firmglobal.com/Confirmit/webservices/")
        javax.xml.datatype.XMLGregorianCalendar createdTo
    );

    @WebMethod(operationName = "GetRouting", action = "http://firmglobal.com/Confirmit/webservices/GetRouting")
    @RequestWrapper(localName = "GetRouting", targetNamespace = "http://firmglobal.com/Confirmit/webservices/", className = "com.nielsen.confirmit.webservices.authoring.GetRouting")
    @ResponseWrapper(localName = "GetRoutingResponse", targetNamespace = "http://firmglobal.com/Confirmit/webservices/", className = "com.nielsen.confirmit.webservices.authoring.GetRoutingResponse")
    @WebResult(name = "GetRoutingResult", targetNamespace = "http://firmglobal.com/Confirmit/webservices/")
    public com.nielsen.confirmit.webservices.authoring.SurveySchema getRouting(

        @WebParam(name = "key", targetNamespace = "http://firmglobal.com/Confirmit/webservices/")
        java.lang.String key,
        @WebParam(name = "projectId", targetNamespace = "http://firmglobal.com/Confirmit/webservices/")
        java.lang.String projectId,
        @WebParam(name = "projectSpecific", targetNamespace = "http://firmglobal.com/Confirmit/webservices/")
        boolean projectSpecific
    );

    @WebMethod(operationName = "AddProject", action = "http://firmglobal.com/Confirmit/webservices/AddProject")
    @RequestWrapper(localName = "AddProject", targetNamespace = "http://firmglobal.com/Confirmit/webservices/", className = "com.nielsen.confirmit.webservices.authoring.AddProject")
    @ResponseWrapper(localName = "AddProjectResponse", targetNamespace = "http://firmglobal.com/Confirmit/webservices/", className = "com.nielsen.confirmit.webservices.authoring.AddProjectResponse")
    @WebResult(name = "AddProjectResult", targetNamespace = "http://firmglobal.com/Confirmit/webservices/")
    public java.lang.String addProject(

        @WebParam(name = "key", targetNamespace = "http://firmglobal.com/Confirmit/webservices/")
        java.lang.String key,
        @WebParam(name = "isPanel", targetNamespace = "http://firmglobal.com/Confirmit/webservices/")
        boolean isPanel
    );

    @WebMethod(operationName = "GetQuestionnaire", action = "http://firmglobal.com/Confirmit/webservices/GetQuestionnaire")
    @RequestWrapper(localName = "GetQuestionnaire", targetNamespace = "http://firmglobal.com/Confirmit/webservices/", className = "com.nielsen.confirmit.webservices.authoring.GetQuestionnaire")
    @ResponseWrapper(localName = "GetQuestionnaireResponse", targetNamespace = "http://firmglobal.com/Confirmit/webservices/", className = "com.nielsen.confirmit.webservices.authoring.GetQuestionnaireResponse")
    @WebResult(name = "GetQuestionnaireResult", targetNamespace = "http://firmglobal.com/Confirmit/webservices/")
    public com.nielsen.confirmit.webservices.authoring.SurveySchema getQuestionnaire(

        @WebParam(name = "key", targetNamespace = "http://firmglobal.com/Confirmit/webservices/")
        java.lang.String key,
        @WebParam(name = "projectId", targetNamespace = "http://firmglobal.com/Confirmit/webservices/")
        java.lang.String projectId,
        @WebParam(name = "projectSpecific", targetNamespace = "http://firmglobal.com/Confirmit/webservices/")
        boolean projectSpecific
    );

    @WebMethod(operationName = "ImportSurvey", action = "http://firmglobal.com/Confirmit/webservices/ImportSurvey")
    @RequestWrapper(localName = "ImportSurvey", targetNamespace = "http://firmglobal.com/Confirmit/webservices/", className = "com.nielsen.confirmit.webservices.authoring.ImportSurvey")
    @ResponseWrapper(localName = "ImportSurveyResponse", targetNamespace = "http://firmglobal.com/Confirmit/webservices/", className = "com.nielsen.confirmit.webservices.authoring.ImportSurveyResponse")
    @WebResult(name = "ImportSurveyResult", targetNamespace = "http://firmglobal.com/Confirmit/webservices/")
    public java.lang.String importSurvey(

        @WebParam(name = "key", targetNamespace = "http://firmglobal.com/Confirmit/webservices/")
        java.lang.String key,
        @WebParam(name = "surveyXml", targetNamespace = "http://firmglobal.com/Confirmit/webservices/")
        java.lang.String surveyXml
    );

    @WebMethod(operationName = "ExportSurvey", action = "http://firmglobal.com/Confirmit/webservices/ExportSurvey")
    @RequestWrapper(localName = "ExportSurvey", targetNamespace = "http://firmglobal.com/Confirmit/webservices/", className = "com.nielsen.confirmit.webservices.authoring.ExportSurvey")
    @ResponseWrapper(localName = "ExportSurveyResponse", targetNamespace = "http://firmglobal.com/Confirmit/webservices/", className = "com.nielsen.confirmit.webservices.authoring.ExportSurveyResponse")
    @WebResult(name = "ExportSurveyResult", targetNamespace = "http://firmglobal.com/Confirmit/webservices/")
    public java.lang.String exportSurvey(

        @WebParam(name = "key", targetNamespace = "http://firmglobal.com/Confirmit/webservices/")
        java.lang.String key,
        @WebParam(name = "projectId", targetNamespace = "http://firmglobal.com/Confirmit/webservices/")
        java.lang.String projectId
    );

    @WebMethod(operationName = "Update", action = "http://firmglobal.com/Confirmit/webservices/Update")
    @RequestWrapper(localName = "Update", targetNamespace = "http://firmglobal.com/Confirmit/webservices/", className = "com.nielsen.confirmit.webservices.authoring.Update")
    @ResponseWrapper(localName = "UpdateResponse", targetNamespace = "http://firmglobal.com/Confirmit/webservices/", className = "com.nielsen.confirmit.webservices.authoring.UpdateResponse")
    public void update(

        @WebParam(name = "key", targetNamespace = "http://firmglobal.com/Confirmit/webservices/")
        java.lang.String key,
        @WebParam(name = "projectId", targetNamespace = "http://firmglobal.com/Confirmit/webservices/")
        java.lang.String projectId,
        @WebParam(name = "schema", targetNamespace = "http://firmglobal.com/Confirmit/webservices/")
        com.nielsen.confirmit.webservices.authoring.SurveySchema schema
    );

    @WebMethod(operationName = "GetQuotas", action = "http://firmglobal.com/Confirmit/webservices/GetQuotas")
    @RequestWrapper(localName = "GetQuotas", targetNamespace = "http://firmglobal.com/Confirmit/webservices/", className = "com.nielsen.confirmit.webservices.authoring.GetQuotas")
    @ResponseWrapper(localName = "GetQuotasResponse", targetNamespace = "http://firmglobal.com/Confirmit/webservices/", className = "com.nielsen.confirmit.webservices.authoring.GetQuotasResponse")
    @WebResult(name = "GetQuotasResult", targetNamespace = "http://firmglobal.com/Confirmit/webservices/")
    public com.nielsen.confirmit.webservices.authoring.SurveySchema getQuotas(

        @WebParam(name = "key", targetNamespace = "http://firmglobal.com/Confirmit/webservices/")
        java.lang.String key,
        @WebParam(name = "projectId", targetNamespace = "http://firmglobal.com/Confirmit/webservices/")
        java.lang.String projectId,
        @WebParam(name = "projectSpecific", targetNamespace = "http://firmglobal.com/Confirmit/webservices/")
        boolean projectSpecific
    );

    @WebMethod(operationName = "GetBenchmarkProjectIds", action = "http://firmglobal.com/Confirmit/webservices/GetBenchmarkProjectIds")
    @RequestWrapper(localName = "GetBenchmarkProjectIds", targetNamespace = "http://firmglobal.com/Confirmit/webservices/", className = "com.nielsen.confirmit.webservices.authoring.GetBenchmarkProjectIds")
    @ResponseWrapper(localName = "GetBenchmarkProjectIdsResponse", targetNamespace = "http://firmglobal.com/Confirmit/webservices/", className = "com.nielsen.confirmit.webservices.authoring.GetBenchmarkProjectIdsResponse")
    @WebResult(name = "GetBenchmarkProjectIdsResult", targetNamespace = "http://firmglobal.com/Confirmit/webservices/")
    public com.nielsen.confirmit.webservices.authoring.ArrayOfString1 getBenchmarkProjectIds(

        @WebParam(name = "key", targetNamespace = "http://firmglobal.com/Confirmit/webservices/")
        java.lang.String key,
        @WebParam(name = "projectId", targetNamespace = "http://firmglobal.com/Confirmit/webservices/")
        java.lang.String projectId
    );

    @WebMethod(operationName = "GetLoopStructure", action = "http://firmglobal.com/Confirmit/webservices/GetLoopStructure")
    @RequestWrapper(localName = "GetLoopStructure", targetNamespace = "http://firmglobal.com/Confirmit/webservices/", className = "com.nielsen.confirmit.webservices.authoring.GetLoopStructure")
    @ResponseWrapper(localName = "GetLoopStructureResponse", targetNamespace = "http://firmglobal.com/Confirmit/webservices/", className = "com.nielsen.confirmit.webservices.authoring.GetLoopStructureResponse")
    @WebResult(name = "GetLoopStructureResult", targetNamespace = "http://firmglobal.com/Confirmit/webservices/")
    public com.nielsen.confirmit.webservices.authoring.SurveySchema getLoopStructure(

        @WebParam(name = "key", targetNamespace = "http://firmglobal.com/Confirmit/webservices/")
        java.lang.String key,
        @WebParam(name = "projectId", targetNamespace = "http://firmglobal.com/Confirmit/webservices/")
        java.lang.String projectId,
        @WebParam(name = "schemaSource", targetNamespace = "http://firmglobal.com/Confirmit/webservices/")
        com.nielsen.confirmit.webservices.authoring.SchemaSourceType schemaSource
    );

    @WebMethod(operationName = "ExportSurveyWithHTMLRemoved", action = "http://firmglobal.com/Confirmit/webservices/ExportSurveyWithHTMLRemoved")
    @RequestWrapper(localName = "ExportSurveyWithHTMLRemoved", targetNamespace = "http://firmglobal.com/Confirmit/webservices/", className = "com.nielsen.confirmit.webservices.authoring.ExportSurveyWithHTMLRemoved")
    @ResponseWrapper(localName = "ExportSurveyWithHTMLRemovedResponse", targetNamespace = "http://firmglobal.com/Confirmit/webservices/", className = "com.nielsen.confirmit.webservices.authoring.ExportSurveyWithHTMLRemovedResponse")
    @WebResult(name = "ExportSurveyWithHTMLRemovedResult", targetNamespace = "http://firmglobal.com/Confirmit/webservices/")
    public java.lang.String exportSurveyWithHTMLRemoved(

        @WebParam(name = "key", targetNamespace = "http://firmglobal.com/Confirmit/webservices/")
        java.lang.String key,
        @WebParam(name = "projectId", targetNamespace = "http://firmglobal.com/Confirmit/webservices/")
        java.lang.String projectId
    );

    @WebMethod(operationName = "GetProjectList", action = "http://firmglobal.com/Confirmit/webservices/GetProjectList")
    @RequestWrapper(localName = "GetProjectList", targetNamespace = "http://firmglobal.com/Confirmit/webservices/", className = "com.nielsen.confirmit.webservices.authoring.GetProjectList")
    @ResponseWrapper(localName = "GetProjectListResponse", targetNamespace = "http://firmglobal.com/Confirmit/webservices/", className = "com.nielsen.confirmit.webservices.authoring.GetProjectListResponse")
    @WebResult(name = "GetProjectListResult", targetNamespace = "http://firmglobal.com/Confirmit/webservices/")
    public com.nielsen.confirmit.webservices.authoring.ProjectListResultSet getProjectList(

        @WebParam(name = "key", targetNamespace = "http://firmglobal.com/Confirmit/webservices/")
        java.lang.String key,
        @WebParam(name = "projectType", targetNamespace = "http://firmglobal.com/Confirmit/webservices/")
        com.nielsen.confirmit.webservices.authoring.ProjectType projectType,
        @WebParam(name = "allProjects", targetNamespace = "http://firmglobal.com/Confirmit/webservices/")
        boolean allProjects,
        @WebParam(name = "token", targetNamespace = "http://firmglobal.com/Confirmit/webservices/")
        com.nielsen.confirmit.webservices.authoring.ProjectListToken token
    );

    @WebMethod(operationName = "GetProjectEmailObjects", action = "http://firmglobal.com/Confirmit/webservices/GetProjectEmailObjects")
    @RequestWrapper(localName = "GetProjectEmailObjects", targetNamespace = "http://firmglobal.com/Confirmit/webservices/", className = "com.nielsen.confirmit.webservices.authoring.GetProjectEmailObjects")
    @ResponseWrapper(localName = "GetProjectEmailObjectsResponse", targetNamespace = "http://firmglobal.com/Confirmit/webservices/", className = "com.nielsen.confirmit.webservices.authoring.GetProjectEmailObjectsResponse")
    @WebResult(name = "GetProjectEmailObjectsResult", targetNamespace = "http://firmglobal.com/Confirmit/webservices/")
    public com.nielsen.confirmit.webservices.authoring.ArrayOfEmailObject getProjectEmailObjects(

        @WebParam(name = "key", targetNamespace = "http://firmglobal.com/Confirmit/webservices/")
        java.lang.String key,
        @WebParam(name = "projectId", targetNamespace = "http://firmglobal.com/Confirmit/webservices/")
        java.lang.String projectId
    );

    @WebMethod(operationName = "ExportSurveyLayout", action = "http://firmglobal.com/Confirmit/webservices/ExportSurveyLayout")
    @RequestWrapper(localName = "ExportSurveyLayout", targetNamespace = "http://firmglobal.com/Confirmit/webservices/", className = "com.nielsen.confirmit.webservices.authoring.ExportSurveyLayout")
    @ResponseWrapper(localName = "ExportSurveyLayoutResponse", targetNamespace = "http://firmglobal.com/Confirmit/webservices/", className = "com.nielsen.confirmit.webservices.authoring.ExportSurveyLayoutResponse")
    @WebResult(name = "ExportSurveyLayoutResult", targetNamespace = "http://firmglobal.com/Confirmit/webservices/")
    public java.lang.String exportSurveyLayout(

        @WebParam(name = "key", targetNamespace = "http://firmglobal.com/Confirmit/webservices/")
        java.lang.String key,
        @WebParam(name = "surveyLayoutId", targetNamespace = "http://firmglobal.com/Confirmit/webservices/")
        java.lang.String surveyLayoutId
    );

    @WebMethod(operationName = "SetCustomProjectInfoField", action = "http://firmglobal.com/Confirmit/webservices/SetCustomProjectInfoField")
    @RequestWrapper(localName = "SetCustomProjectInfoField", targetNamespace = "http://firmglobal.com/Confirmit/webservices/", className = "com.nielsen.confirmit.webservices.authoring.SetCustomProjectInfoField")
    @ResponseWrapper(localName = "SetCustomProjectInfoFieldResponse", targetNamespace = "http://firmglobal.com/Confirmit/webservices/", className = "com.nielsen.confirmit.webservices.authoring.SetCustomProjectInfoFieldResponse")
    public void setCustomProjectInfoField(

        @WebParam(name = "key", targetNamespace = "http://firmglobal.com/Confirmit/webservices/")
        java.lang.String key,
        @WebParam(name = "projectId", targetNamespace = "http://firmglobal.com/Confirmit/webservices/")
        java.lang.String projectId,
        @WebParam(name = "fieldId", targetNamespace = "http://firmglobal.com/Confirmit/webservices/")
        java.lang.String fieldId,
        @WebParam(name = "fieldValue", targetNamespace = "http://firmglobal.com/Confirmit/webservices/")
        java.lang.String fieldValue
    );

    @WebMethod(operationName = "GetDatabaseLastCompiled", action = "http://firmglobal.com/Confirmit/webservices/GetDatabaseLastCompiled")
    @RequestWrapper(localName = "GetDatabaseLastCompiled", targetNamespace = "http://firmglobal.com/Confirmit/webservices/", className = "com.nielsen.confirmit.webservices.authoring.GetDatabaseLastCompiled")
    @ResponseWrapper(localName = "GetDatabaseLastCompiledResponse", targetNamespace = "http://firmglobal.com/Confirmit/webservices/", className = "com.nielsen.confirmit.webservices.authoring.GetDatabaseLastCompiledResponse")
    @WebResult(name = "GetDatabaseLastCompiledResult", targetNamespace = "http://firmglobal.com/Confirmit/webservices/")
    public javax.xml.datatype.XMLGregorianCalendar getDatabaseLastCompiled(

        @WebParam(name = "key", targetNamespace = "http://firmglobal.com/Confirmit/webservices/")
        java.lang.String key,
        @WebParam(name = "projectId", targetNamespace = "http://firmglobal.com/Confirmit/webservices/")
        java.lang.String projectId,
        @WebParam(name = "dbType", targetNamespace = "http://firmglobal.com/Confirmit/webservices/")
        com.nielsen.confirmit.webservices.authoring.DatabaseType dbType
    );
}
