package com.nielsen.confirmit.webservices.authoring;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.3.4
 * 2019-11-07T17:53:20.783+05:30
 * Generated source version: 3.3.4
 *
 */
@WebServiceClient(name = "Authoring",
                  wsdlLocation = "file:/E:/Nielson Project/Projects/Test/confirmit/src/main/resources/wsdl/Authoring_18_0.wsdl",
                  targetNamespace = "http://firmglobal.com/Confirmit/webservices/")
public class Authoring extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://firmglobal.com/Confirmit/webservices/", "Authoring");
    public final static QName AuthoringSoap = new QName("http://firmglobal.com/Confirmit/webservices/", "AuthoringSoap");
    public final static QName AuthoringSoap12 = new QName("http://firmglobal.com/Confirmit/webservices/", "AuthoringSoap12");
    static {
        URL url = null;
        try {
            url = new URL("file:/E:/Nielson Project/Projects/Test/confirmit/src/main/resources/wsdl/Authoring_18_0.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(Authoring.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/E:/Nielson Project/Projects/Test/confirmit/src/main/resources/wsdl/Authoring_18_0.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public Authoring(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public Authoring(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Authoring() {
        super(WSDL_LOCATION, SERVICE);
    }

    public Authoring(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public Authoring(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public Authoring(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns AuthoringSoap
     */
    @WebEndpoint(name = "AuthoringSoap")
    public AuthoringSoap getAuthoringSoap() {
        return super.getPort(AuthoringSoap, AuthoringSoap.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AuthoringSoap
     */
    @WebEndpoint(name = "AuthoringSoap")
    public AuthoringSoap getAuthoringSoap(WebServiceFeature... features) {
        return super.getPort(AuthoringSoap, AuthoringSoap.class, features);
    }


    /**
     *
     * @return
     *     returns AuthoringSoap
     */
    @WebEndpoint(name = "AuthoringSoap12")
    public AuthoringSoap getAuthoringSoap12() {
        return super.getPort(AuthoringSoap12, AuthoringSoap.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AuthoringSoap
     */
    @WebEndpoint(name = "AuthoringSoap12")
    public AuthoringSoap getAuthoringSoap12(WebServiceFeature... features) {
        return super.getPort(AuthoringSoap12, AuthoringSoap.class, features);
    }

}
