package com.nielsen.confirmit.webservices.surveydata;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.4
 * 2019-11-15T12:28:01.685+05:30
 * Generated source version: 3.3.4
 *
 */
@WebService(targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/", name = "SurveyDataSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface SurveyDataSoap {

    @WebMethod(operationName = "UpdateRespondentsGeneral", action = "http://firmglobal.com/Confirmit/webservices/8.5/UpdateRespondentsGeneral")
    @RequestWrapper(localName = "UpdateRespondentsGeneral", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/", className = "com.nielsen.confirmit.webservices.surveydata.UpdateRespondentsGeneral")
    @ResponseWrapper(localName = "UpdateRespondentsGeneralResponse", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/", className = "com.nielsen.confirmit.webservices.surveydata.UpdateRespondentsGeneralResponse")
    @WebResult(name = "UpdateRespondentsGeneralResult", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/")
    public com.nielsen.confirmit.webservices.surveydata.ArrayOfErrorMessage updateRespondentsGeneral(

        @WebParam(name = "key", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/")
        java.lang.String key,
        @WebParam(name = "projectId", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/")
        java.lang.String projectId,
        @WebParam(name = "data", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/")
        com.nielsen.confirmit.webservices.surveydata.ConfirmitData data,
        @WebParam(name = "validate", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/")
        boolean validate,
        @WebParam(name = "merge", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/")
        boolean merge,
        @WebParam(name = "uniqueKey", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/")
        java.lang.String uniqueKey,
        @WebParam(name = "inTransaction", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/")
        boolean inTransaction,
        @WebParam(name = "transactionKey", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/")
        int transactionKey
    );

    @WebMethod(operationName = "GetRespondentEmailLogByTime", action = "http://firmglobal.com/Confirmit/webservices/8.5/GetRespondentEmailLogByTime")
    @RequestWrapper(localName = "GetRespondentEmailLogByTime", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/", className = "com.nielsen.confirmit.webservices.surveydata.GetRespondentEmailLogByTime")
    @ResponseWrapper(localName = "GetRespondentEmailLogByTimeResponse", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/", className = "com.nielsen.confirmit.webservices.surveydata.GetRespondentEmailLogByTimeResponse")
    @WebResult(name = "GetRespondentEmailLogByTimeResult", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/")
    public com.nielsen.confirmit.webservices.surveydata.GetRespondentEmailLogByTimeResponse.GetRespondentEmailLogByTimeResult getRespondentEmailLogByTime(

        @WebParam(name = "key", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/")
        java.lang.String key,
        @WebParam(name = "projectId", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/")
        java.lang.String projectId,
        @WebParam(name = "fieldNames", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/")
        com.nielsen.confirmit.webservices.surveydata.ArrayOfString1 fieldNames,
        @WebParam(name = "from", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/")
        javax.xml.datatype.XMLGregorianCalendar from,
        @WebParam(name = "to", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/")
        javax.xml.datatype.XMLGregorianCalendar to
    );

    @WebMethod(operationName = "GetRespondents", action = "http://firmglobal.com/Confirmit/webservices/8.5/GetRespondents")
    @RequestWrapper(localName = "GetRespondents", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/", className = "com.nielsen.confirmit.webservices.surveydata.GetRespondents")
    @ResponseWrapper(localName = "GetRespondentsResponse", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/", className = "com.nielsen.confirmit.webservices.surveydata.GetRespondentsResponse")
    @WebResult(name = "GetRespondentsResult", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/")
    public com.nielsen.confirmit.webservices.surveydata.GetRespondentsResponse.GetRespondentsResult getRespondents(

        @WebParam(name = "key", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/")
        java.lang.String key,
        @WebParam(name = "respondentTransferDef", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/")
        com.nielsen.confirmit.webservices.surveydata.RespondentTransferDef respondentTransferDef
    );

    @WebMethod(operationName = "UpdateExistingRespondentsGeneralWithCatiScheduling", action = "http://firmglobal.com/Confirmit/webservices/8.5/UpdateExistingRespondentsGeneralWithCatiScheduling")
    @RequestWrapper(localName = "UpdateExistingRespondentsGeneralWithCatiScheduling", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/", className = "com.nielsen.confirmit.webservices.surveydata.UpdateExistingRespondentsGeneralWithCatiScheduling")
    @ResponseWrapper(localName = "UpdateExistingRespondentsGeneralWithCatiSchedulingResponse", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/", className = "com.nielsen.confirmit.webservices.surveydata.UpdateExistingRespondentsGeneralWithCatiSchedulingResponse")
    @WebResult(name = "UpdateExistingRespondentsGeneralWithCatiSchedulingResult", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/")
    public com.nielsen.confirmit.webservices.surveydata.ArrayOfErrorMessage updateExistingRespondentsGeneralWithCatiScheduling(

        @WebParam(name = "key", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/")
        java.lang.String key,
        @WebParam(name = "projectId", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/")
        java.lang.String projectId,
        @WebParam(name = "data", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/")
        com.nielsen.confirmit.webservices.surveydata.ConfirmitData data,
        @WebParam(name = "validate", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/")
        boolean validate,
        @WebParam(name = "uniqueKey", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/")
        java.lang.String uniqueKey,
        @WebParam(name = "inTransaction", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/")
        boolean inTransaction,
        @WebParam(name = "transactionKey", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/")
        int transactionKey,
        @WebParam(name = "schedulingMode", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/")
        com.nielsen.confirmit.webservices.surveydata.CatiScheduling schedulingMode
    );

    @WebMethod(operationName = "GetDataGeneral", action = "http://firmglobal.com/Confirmit/webservices/8.5/GetDataGeneral")
    @RequestWrapper(localName = "GetDataGeneral", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/", className = "com.nielsen.confirmit.webservices.surveydata.GetDataGeneral")
    @ResponseWrapper(localName = "GetDataGeneralResponse", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/", className = "com.nielsen.confirmit.webservices.surveydata.GetDataGeneralResponse")
    @WebResult(name = "GetDataGeneralResult", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/")
    public com.nielsen.confirmit.webservices.surveydata.ConfirmitDataResult getDataGeneral(

        @WebParam(name = "key", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/")
        java.lang.String key,
        @WebParam(name = "transferDef", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/")
        com.nielsen.confirmit.webservices.surveydata.TransferDefBase transferDef,
        @WebParam(name = "token", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/")
        com.nielsen.confirmit.webservices.surveydata.ResponseToken token
    );

    @WebMethod(operationName = "UpdateExistingRespondents", action = "http://firmglobal.com/Confirmit/webservices/8.5/UpdateExistingRespondents")
    @RequestWrapper(localName = "UpdateExistingRespondents", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/", className = "com.nielsen.confirmit.webservices.surveydata.UpdateExistingRespondents")
    @ResponseWrapper(localName = "UpdateExistingRespondentsResponse", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/", className = "com.nielsen.confirmit.webservices.surveydata.UpdateExistingRespondentsResponse")
    @WebResult(name = "UpdateExistingRespondentsResult", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/")
    public com.nielsen.confirmit.webservices.surveydata.ArrayOfErrorMessage updateExistingRespondents(

        @WebParam(name = "key", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/")
        java.lang.String key,
        @WebParam(name = "projectId", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/")
        java.lang.String projectId,
        @WebParam(name = "ds", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/")
        com.nielsen.confirmit.webservices.surveydata.UpdateExistingRespondents.Ds ds,
        @WebParam(name = "validate", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/")
        boolean validate,
        @WebParam(name = "uniqueKey", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/")
        java.lang.String uniqueKey,
        @WebParam(name = "inTransaction", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/")
        boolean inTransaction,
        @WebParam(name = "transactionKey", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/")
        int transactionKey
    );

    @WebMethod(operationName = "GetRespondentEmailLogByTask", action = "http://firmglobal.com/Confirmit/webservices/8.5/GetRespondentEmailLogByTask")
    @RequestWrapper(localName = "GetRespondentEmailLogByTask", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/", className = "com.nielsen.confirmit.webservices.surveydata.GetRespondentEmailLogByTask")
    @ResponseWrapper(localName = "GetRespondentEmailLogByTaskResponse", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/", className = "com.nielsen.confirmit.webservices.surveydata.GetRespondentEmailLogByTaskResponse")
    @WebResult(name = "GetRespondentEmailLogByTaskResult", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/")
    public com.nielsen.confirmit.webservices.surveydata.GetRespondentEmailLogByTaskResponse.GetRespondentEmailLogByTaskResult getRespondentEmailLogByTask(

        @WebParam(name = "key", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/")
        java.lang.String key,
        @WebParam(name = "projectId", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/")
        java.lang.String projectId,
        @WebParam(name = "fieldNames", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/")
        com.nielsen.confirmit.webservices.surveydata.ArrayOfString1 fieldNames,
        @WebParam(name = "taskId", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/")
        long taskId
    );

    @WebMethod(operationName = "UpdateExistingRespondentsGeneral", action = "http://firmglobal.com/Confirmit/webservices/8.5/UpdateExistingRespondentsGeneral")
    @RequestWrapper(localName = "UpdateExistingRespondentsGeneral", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/", className = "com.nielsen.confirmit.webservices.surveydata.UpdateExistingRespondentsGeneral")
    @ResponseWrapper(localName = "UpdateExistingRespondentsGeneralResponse", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/", className = "com.nielsen.confirmit.webservices.surveydata.UpdateExistingRespondentsGeneralResponse")
    @WebResult(name = "UpdateExistingRespondentsGeneralResult", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/")
    public com.nielsen.confirmit.webservices.surveydata.ArrayOfErrorMessage updateExistingRespondentsGeneral(

        @WebParam(name = "key", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/")
        java.lang.String key,
        @WebParam(name = "projectId", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/")
        java.lang.String projectId,
        @WebParam(name = "data", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/")
        com.nielsen.confirmit.webservices.surveydata.ConfirmitData data,
        @WebParam(name = "validate", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/")
        boolean validate,
        @WebParam(name = "uniqueKey", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/")
        java.lang.String uniqueKey,
        @WebParam(name = "inTransaction", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/")
        boolean inTransaction,
        @WebParam(name = "transactionKey", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/")
        int transactionKey
    );

    @WebMethod(operationName = "RemoveRespondentUniqueKey", action = "http://firmglobal.com/Confirmit/webservices/8.5/RemoveRespondentUniqueKey")
    @RequestWrapper(localName = "RemoveRespondentUniqueKey", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/", className = "com.nielsen.confirmit.webservices.surveydata.RemoveRespondentUniqueKey")
    @ResponseWrapper(localName = "RemoveRespondentUniqueKeyResponse", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/", className = "com.nielsen.confirmit.webservices.surveydata.RemoveRespondentUniqueKeyResponse")
    public void removeRespondentUniqueKey(

        @WebParam(name = "key", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/")
        java.lang.String key,
        @WebParam(name = "projectId", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/")
        java.lang.String projectId,
        @WebParam(name = "uniqueKey", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/")
        java.lang.String uniqueKey
    );

    @WebMethod(operationName = "GetRespondentEmailLogByTimeGeneral", action = "http://firmglobal.com/Confirmit/webservices/8.5/GetRespondentEmailLogByTimeGeneral")
    @RequestWrapper(localName = "GetRespondentEmailLogByTimeGeneral", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/", className = "com.nielsen.confirmit.webservices.surveydata.GetRespondentEmailLogByTimeGeneral")
    @ResponseWrapper(localName = "GetRespondentEmailLogByTimeGeneralResponse", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/", className = "com.nielsen.confirmit.webservices.surveydata.GetRespondentEmailLogByTimeGeneralResponse")
    @WebResult(name = "GetRespondentEmailLogByTimeGeneralResult", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/")
    public com.nielsen.confirmit.webservices.surveydata.ConfirmitData getRespondentEmailLogByTimeGeneral(

        @WebParam(name = "key", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/")
        java.lang.String key,
        @WebParam(name = "projectId", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/")
        java.lang.String projectId,
        @WebParam(name = "fieldNames", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/")
        com.nielsen.confirmit.webservices.surveydata.ArrayOfString1 fieldNames,
        @WebParam(name = "from", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/")
        javax.xml.datatype.XMLGregorianCalendar from,
        @WebParam(name = "to", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/")
        javax.xml.datatype.XMLGregorianCalendar to
    );

    @WebMethod(operationName = "GetChangedData", action = "http://firmglobal.com/Confirmit/webservices/8.5/GetChangedData")
    @RequestWrapper(localName = "GetChangedData", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/", className = "com.nielsen.confirmit.webservices.surveydata.GetChangedData")
    @ResponseWrapper(localName = "GetChangedDataResponse", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/", className = "com.nielsen.confirmit.webservices.surveydata.GetChangedDataResponse")
    @WebResult(name = "GetChangedDataResult", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/")
    public com.nielsen.confirmit.webservices.surveydata.ChangedDataResult getChangedData(

        @WebParam(name = "key", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/")
        java.lang.String key,
        @WebParam(name = "transferDef", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/")
        com.nielsen.confirmit.webservices.surveydata.TransferDef transferDef,
        @WebParam(name = "token", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/")
        com.nielsen.confirmit.webservices.surveydata.ResponseToken token,
        @WebParam(name = "lastSynchronizedVersion", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/")
        long lastSynchronizedVersion
    );

    @WebMethod(operationName = "DeleteRespondents", action = "http://firmglobal.com/Confirmit/webservices/8.5/DeleteRespondents")
    @RequestWrapper(localName = "DeleteRespondents", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/", className = "com.nielsen.confirmit.webservices.surveydata.DeleteRespondents")
    @ResponseWrapper(localName = "DeleteRespondentsResponse", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/", className = "com.nielsen.confirmit.webservices.surveydata.DeleteRespondentsResponse")
    @WebResult(name = "DeleteRespondentsResult", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/")
    public int deleteRespondents(

        @WebParam(name = "key", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/")
        java.lang.String key,
        @WebParam(name = "projectId", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/")
        java.lang.String projectId,
        @WebParam(name = "keyName", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/")
        java.lang.String keyName,
        @WebParam(name = "keyValues", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/")
        com.nielsen.confirmit.webservices.surveydata.ArrayOfString1 keyValues
    );

    @WebMethod(operationName = "GetTransactionStatus", action = "http://firmglobal.com/Confirmit/webservices/8.5/GetTransactionStatus")
    @RequestWrapper(localName = "GetTransactionStatus", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/", className = "com.nielsen.confirmit.webservices.surveydata.GetTransactionStatus")
    @ResponseWrapper(localName = "GetTransactionStatusResponse", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/", className = "com.nielsen.confirmit.webservices.surveydata.GetTransactionStatusResponse")
    @WebResult(name = "GetTransactionStatusResult", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/")
    public com.nielsen.confirmit.webservices.surveydata.GetTransactionStatusResponse.GetTransactionStatusResult getTransactionStatus(

        @WebParam(name = "key", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/")
        java.lang.String key,
        @WebParam(name = "transactionKey", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/")
        int transactionKey
    );

    @WebMethod(operationName = "UpdateData", action = "http://firmglobal.com/Confirmit/webservices/8.5/UpdateData")
    @RequestWrapper(localName = "UpdateData", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/", className = "com.nielsen.confirmit.webservices.surveydata.UpdateData")
    @ResponseWrapper(localName = "UpdateDataResponse", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/", className = "com.nielsen.confirmit.webservices.surveydata.UpdateDataResponse")
    @WebResult(name = "UpdateDataResult", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/")
    public com.nielsen.confirmit.webservices.surveydata.ArrayOfErrorMessage updateData(

        @WebParam(name = "key", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/")
        java.lang.String key,
        @WebParam(name = "transferDef", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/")
        com.nielsen.confirmit.webservices.surveydata.TransferDef transferDef,
        @WebParam(name = "ds", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/")
        com.nielsen.confirmit.webservices.surveydata.UpdateData.Ds ds,
        @WebParam(name = "applyRules", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/")
        boolean applyRules,
        @WebParam(name = "inTransaction", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/")
        boolean inTransaction,
        @WebParam(name = "transactionKey", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/")
        int transactionKey
    );

    @WebMethod(operationName = "UpdateExistingRespondentsWithCatiScheduling", action = "http://firmglobal.com/Confirmit/webservices/8.5/UpdateExistingRespondentsWithCatiScheduling")
    @RequestWrapper(localName = "UpdateExistingRespondentsWithCatiScheduling", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/", className = "com.nielsen.confirmit.webservices.surveydata.UpdateExistingRespondentsWithCatiScheduling")
    @ResponseWrapper(localName = "UpdateExistingRespondentsWithCatiSchedulingResponse", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/", className = "com.nielsen.confirmit.webservices.surveydata.UpdateExistingRespondentsWithCatiSchedulingResponse")
    @WebResult(name = "UpdateExistingRespondentsWithCatiSchedulingResult", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/")
    public com.nielsen.confirmit.webservices.surveydata.ArrayOfErrorMessage updateExistingRespondentsWithCatiScheduling(

        @WebParam(name = "key", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/")
        java.lang.String key,
        @WebParam(name = "projectId", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/")
        java.lang.String projectId,
        @WebParam(name = "ds", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/")
        com.nielsen.confirmit.webservices.surveydata.UpdateExistingRespondentsWithCatiScheduling.Ds ds,
        @WebParam(name = "validate", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/")
        boolean validate,
        @WebParam(name = "uniqueKey", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/")
        java.lang.String uniqueKey,
        @WebParam(name = "inTransaction", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/")
        boolean inTransaction,
        @WebParam(name = "transactionKey", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/")
        int transactionKey,
        @WebParam(name = "schedulingMode", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/")
        com.nielsen.confirmit.webservices.surveydata.CatiScheduling schedulingMode
    );

    @WebMethod(operationName = "GetDataByProjectGeneral", action = "http://firmglobal.com/Confirmit/webservices/8.5/GetDataByProjectGeneral")
    @RequestWrapper(localName = "GetDataByProjectGeneral", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/", className = "com.nielsen.confirmit.webservices.surveydata.GetDataByProjectGeneral")
    @ResponseWrapper(localName = "GetDataByProjectGeneralResponse", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/", className = "com.nielsen.confirmit.webservices.surveydata.GetDataByProjectGeneralResponse")
    @WebResult(name = "GetDataByProjectGeneralResult", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/")
    public com.nielsen.confirmit.webservices.surveydata.ConfirmitDataResult getDataByProjectGeneral(

        @WebParam(name = "key", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/")
        java.lang.String key,
        @WebParam(name = "projectId", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/")
        java.lang.String projectId,
        @WebParam(name = "includeSystemVariables", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/")
        boolean includeSystemVariables,
        @WebParam(name = "databaseType", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/")
        com.nielsen.confirmit.webservices.surveydata.DatabaseType databaseType,
        @WebParam(name = "token", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/")
        com.nielsen.confirmit.webservices.surveydata.ResponseToken token
    );

    @WebMethod(operationName = "GetRespondentsTokenized", action = "http://firmglobal.com/Confirmit/webservices/8.5/GetRespondentsTokenized")
    @RequestWrapper(localName = "GetRespondentsTokenized", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/", className = "com.nielsen.confirmit.webservices.surveydata.GetRespondentsTokenized")
    @ResponseWrapper(localName = "GetRespondentsTokenizedResponse", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/", className = "com.nielsen.confirmit.webservices.surveydata.GetRespondentsTokenizedResponse")
    @WebResult(name = "GetRespondentsTokenizedResult", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/")
    public com.nielsen.confirmit.webservices.surveydata.RespondentTransferResult getRespondentsTokenized(

        @WebParam(name = "key", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/")
        java.lang.String key,
        @WebParam(name = "respondentTransferDef", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/")
        com.nielsen.confirmit.webservices.surveydata.RespondentTransferDef respondentTransferDef,
        @WebParam(name = "token", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/")
        com.nielsen.confirmit.webservices.surveydata.RespondentToken token
    );

    @WebMethod(operationName = "GetDataByProject", action = "http://firmglobal.com/Confirmit/webservices/8.5/GetDataByProject")
    @RequestWrapper(localName = "GetDataByProject", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/", className = "com.nielsen.confirmit.webservices.surveydata.GetDataByProject")
    @ResponseWrapper(localName = "GetDataByProjectResponse", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/", className = "com.nielsen.confirmit.webservices.surveydata.GetDataByProjectResponse")
    @WebResult(name = "GetDataByProjectResult", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/")
    public com.nielsen.confirmit.webservices.surveydata.TransferResult getDataByProject(

        @WebParam(name = "key", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/")
        java.lang.String key,
        @WebParam(name = "projectId", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/")
        java.lang.String projectId,
        @WebParam(name = "includeSystemVariables", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/")
        boolean includeSystemVariables,
        @WebParam(name = "databaseType", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/")
        com.nielsen.confirmit.webservices.surveydata.DatabaseType databaseType,
        @WebParam(name = "token", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/")
        com.nielsen.confirmit.webservices.surveydata.ResponseToken token
    );

    @WebMethod(operationName = "ConstructWhereClause", action = "http://firmglobal.com/Confirmit/webservices/8.5/ConstructWhereClause")
    @RequestWrapper(localName = "ConstructWhereClause", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/", className = "com.nielsen.confirmit.webservices.surveydata.ConstructWhereClause")
    @ResponseWrapper(localName = "ConstructWhereClauseResponse", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/", className = "com.nielsen.confirmit.webservices.surveydata.ConstructWhereClauseResponse")
    @WebResult(name = "ConstructWhereClauseResult", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/")
    public com.nielsen.confirmit.webservices.surveydata.WhereClause constructWhereClause(

        @WebParam(name = "key", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/")
        java.lang.String key,
        @WebParam(name = "projectId", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/")
        java.lang.String projectId,
        @WebParam(name = "dbType", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/")
        com.nielsen.confirmit.webservices.surveydata.DatabaseType dbType,
        @WebParam(name = "expressionVariableType", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/")
        com.nielsen.confirmit.webservices.surveydata.ExpressionVariableType expressionVariableType,
        @WebParam(name = "expression", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/")
        java.lang.String expression
    );

    @WebMethod(operationName = "GetLevelByName", action = "http://firmglobal.com/Confirmit/webservices/8.5/GetLevelByName")
    @RequestWrapper(localName = "GetLevelByName", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/", className = "com.nielsen.confirmit.webservices.surveydata.GetLevelByName")
    @ResponseWrapper(localName = "GetLevelByNameResponse", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/", className = "com.nielsen.confirmit.webservices.surveydata.GetLevelByNameResponse")
    @WebResult(name = "GetLevelByNameResult", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/")
    public com.nielsen.confirmit.webservices.surveydata.TransferResult getLevelByName(

        @WebParam(name = "key", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/")
        java.lang.String key,
        @WebParam(name = "projectId", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/")
        java.lang.String projectId,
        @WebParam(name = "levelNames", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/")
        com.nielsen.confirmit.webservices.surveydata.ArrayOfString1 levelNames,
        @WebParam(name = "includeSystemVariables", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/")
        boolean includeSystemVariables,
        @WebParam(name = "databaseType", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/")
        com.nielsen.confirmit.webservices.surveydata.DatabaseType databaseType,
        @WebParam(name = "token", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/")
        com.nielsen.confirmit.webservices.surveydata.ResponseToken token
    );

    @WebMethod(operationName = "GetInterviewProgressStats", action = "http://firmglobal.com/Confirmit/webservices/8.5/GetInterviewProgressStats")
    @RequestWrapper(localName = "GetInterviewProgressStats", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/", className = "com.nielsen.confirmit.webservices.surveydata.GetInterviewProgressStats")
    @ResponseWrapper(localName = "GetInterviewProgressStatsResponse", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/", className = "com.nielsen.confirmit.webservices.surveydata.GetInterviewProgressStatsResponse")
    @WebResult(name = "GetInterviewProgressStatsResult", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/")
    public com.nielsen.confirmit.webservices.surveydata.ArrayOfInterviewProgressStats getInterviewProgressStats(

        @WebParam(name = "key", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/")
        java.lang.String key,
        @WebParam(name = "projectId", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/")
        java.lang.String projectId
    );

    @WebMethod(operationName = "ResetConfigSettings", action = "http://firmglobal.com/Confirmit/webservices/8.5/ResetConfigSettings")
    @RequestWrapper(localName = "ResetConfigSettings", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/", className = "com.nielsen.confirmit.webservices.surveydata.ResetConfigSettings")
    @ResponseWrapper(localName = "ResetConfigSettingsResponse", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/", className = "com.nielsen.confirmit.webservices.surveydata.ResetConfigSettingsResponse")
    public void resetConfigSettings(

        @WebParam(name = "key", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/")
        java.lang.String key
    );

    @WebMethod(operationName = "DeleteAllRespondents", action = "http://firmglobal.com/Confirmit/webservices/8.5/DeleteAllRespondents")
    @RequestWrapper(localName = "DeleteAllRespondents", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/", className = "com.nielsen.confirmit.webservices.surveydata.DeleteAllRespondents")
    @ResponseWrapper(localName = "DeleteAllRespondentsResponse", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/", className = "com.nielsen.confirmit.webservices.surveydata.DeleteAllRespondentsResponse")
    @WebResult(name = "DeleteAllRespondentsResult", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/")
    public int deleteAllRespondents(

        @WebParam(name = "key", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/")
        java.lang.String key,
        @WebParam(name = "projectId", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/")
        java.lang.String projectId
    );

    @WebMethod(operationName = "GetRespondentEmailLogByUniqueKey", action = "http://firmglobal.com/Confirmit/webservices/8.5/GetRespondentEmailLogByUniqueKey")
    @RequestWrapper(localName = "GetRespondentEmailLogByUniqueKey", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/", className = "com.nielsen.confirmit.webservices.surveydata.GetRespondentEmailLogByUniqueKey")
    @ResponseWrapper(localName = "GetRespondentEmailLogByUniqueKeyResponse", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/", className = "com.nielsen.confirmit.webservices.surveydata.GetRespondentEmailLogByUniqueKeyResponse")
    @WebResult(name = "GetRespondentEmailLogByUniqueKeyResult", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/")
    public com.nielsen.confirmit.webservices.surveydata.GetRespondentEmailLogByUniqueKeyResponse.GetRespondentEmailLogByUniqueKeyResult getRespondentEmailLogByUniqueKey(

        @WebParam(name = "key", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/")
        java.lang.String key,
        @WebParam(name = "projectId", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/")
        java.lang.String projectId,
        @WebParam(name = "fieldNames", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/")
        com.nielsen.confirmit.webservices.surveydata.ArrayOfString1 fieldNames,
        @WebParam(name = "keyName", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/")
        java.lang.String keyName,
        @WebParam(name = "keyValues", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/")
        com.nielsen.confirmit.webservices.surveydata.ArrayOfString1 keyValues
    );

    @WebMethod(operationName = "GetRespondentEmailLogByUniqueKeyGeneral", action = "http://firmglobal.com/Confirmit/webservices/8.5/GetRespondentEmailLogByUniqueKeyGeneral")
    @RequestWrapper(localName = "GetRespondentEmailLogByUniqueKeyGeneral", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/", className = "com.nielsen.confirmit.webservices.surveydata.GetRespondentEmailLogByUniqueKeyGeneral")
    @ResponseWrapper(localName = "GetRespondentEmailLogByUniqueKeyGeneralResponse", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/", className = "com.nielsen.confirmit.webservices.surveydata.GetRespondentEmailLogByUniqueKeyGeneralResponse")
    @WebResult(name = "GetRespondentEmailLogByUniqueKeyGeneralResult", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/")
    public com.nielsen.confirmit.webservices.surveydata.ConfirmitData getRespondentEmailLogByUniqueKeyGeneral(

        @WebParam(name = "key", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/")
        java.lang.String key,
        @WebParam(name = "projectId", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/")
        java.lang.String projectId,
        @WebParam(name = "fieldNames", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/")
        com.nielsen.confirmit.webservices.surveydata.ArrayOfString1 fieldNames,
        @WebParam(name = "keyName", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/")
        java.lang.String keyName,
        @WebParam(name = "keyValues", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/")
        com.nielsen.confirmit.webservices.surveydata.ArrayOfString1 keyValues
    );

    @WebMethod(operationName = "IsRespondentUniqueKey", action = "http://firmglobal.com/Confirmit/webservices/8.5/IsRespondentUniqueKey")
    @RequestWrapper(localName = "IsRespondentUniqueKey", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/", className = "com.nielsen.confirmit.webservices.surveydata.IsRespondentUniqueKey")
    @ResponseWrapper(localName = "IsRespondentUniqueKeyResponse", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/", className = "com.nielsen.confirmit.webservices.surveydata.IsRespondentUniqueKeyResponse")
    @WebResult(name = "IsRespondentUniqueKeyResult", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/")
    public boolean isRespondentUniqueKey(

        @WebParam(name = "key", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/")
        java.lang.String key,
        @WebParam(name = "projectId", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/")
        java.lang.String projectId,
        @WebParam(name = "uniqueKey", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/")
        java.lang.String uniqueKey
    );

    @WebMethod(operationName = "GetLevelByNameGeneral", action = "http://firmglobal.com/Confirmit/webservices/8.5/GetLevelByNameGeneral")
    @RequestWrapper(localName = "GetLevelByNameGeneral", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/", className = "com.nielsen.confirmit.webservices.surveydata.GetLevelByNameGeneral")
    @ResponseWrapper(localName = "GetLevelByNameGeneralResponse", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/", className = "com.nielsen.confirmit.webservices.surveydata.GetLevelByNameGeneralResponse")
    @WebResult(name = "GetLevelByNameGeneralResult", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/")
    public com.nielsen.confirmit.webservices.surveydata.ConfirmitDataResult getLevelByNameGeneral(

        @WebParam(name = "key", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/")
        java.lang.String key,
        @WebParam(name = "projectId", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/")
        java.lang.String projectId,
        @WebParam(name = "levelNames", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/")
        com.nielsen.confirmit.webservices.surveydata.ArrayOfString1 levelNames,
        @WebParam(name = "includeSystemVariables", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/")
        boolean includeSystemVariables,
        @WebParam(name = "databaseType", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/")
        com.nielsen.confirmit.webservices.surveydata.DatabaseType databaseType,
        @WebParam(name = "token", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/")
        com.nielsen.confirmit.webservices.surveydata.ResponseToken token
    );

    @WebMethod(operationName = "UpdateRespondentsGeneralWithCatiScheduling", action = "http://firmglobal.com/Confirmit/webservices/8.5/UpdateRespondentsGeneralWithCatiScheduling")
    @RequestWrapper(localName = "UpdateRespondentsGeneralWithCatiScheduling", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/", className = "com.nielsen.confirmit.webservices.surveydata.UpdateRespondentsGeneralWithCatiScheduling")
    @ResponseWrapper(localName = "UpdateRespondentsGeneralWithCatiSchedulingResponse", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/", className = "com.nielsen.confirmit.webservices.surveydata.UpdateRespondentsGeneralWithCatiSchedulingResponse")
    @WebResult(name = "UpdateRespondentsGeneralWithCatiSchedulingResult", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/")
    public com.nielsen.confirmit.webservices.surveydata.ArrayOfErrorMessage updateRespondentsGeneralWithCatiScheduling(

        @WebParam(name = "key", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/")
        java.lang.String key,
        @WebParam(name = "projectId", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/")
        java.lang.String projectId,
        @WebParam(name = "data", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/")
        com.nielsen.confirmit.webservices.surveydata.ConfirmitData data,
        @WebParam(name = "validate", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/")
        boolean validate,
        @WebParam(name = "merge", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/")
        boolean merge,
        @WebParam(name = "uniqueKey", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/")
        java.lang.String uniqueKey,
        @WebParam(name = "inTransaction", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/")
        boolean inTransaction,
        @WebParam(name = "transactionKey", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/")
        int transactionKey,
        @WebParam(name = "schedulingMode", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/")
        com.nielsen.confirmit.webservices.surveydata.CatiScheduling schedulingMode
    );

    @WebMethod(operationName = "UpdateRespondentsWithCatiScheduling", action = "http://firmglobal.com/Confirmit/webservices/8.5/UpdateRespondentsWithCatiScheduling")
    @RequestWrapper(localName = "UpdateRespondentsWithCatiScheduling", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/", className = "com.nielsen.confirmit.webservices.surveydata.UpdateRespondentsWithCatiScheduling")
    @ResponseWrapper(localName = "UpdateRespondentsWithCatiSchedulingResponse", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/", className = "com.nielsen.confirmit.webservices.surveydata.UpdateRespondentsWithCatiSchedulingResponse")
    @WebResult(name = "UpdateRespondentsWithCatiSchedulingResult", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/")
    public com.nielsen.confirmit.webservices.surveydata.ArrayOfErrorMessage updateRespondentsWithCatiScheduling(

        @WebParam(name = "key", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/")
        java.lang.String key,
        @WebParam(name = "projectId", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/")
        java.lang.String projectId,
        @WebParam(name = "ds", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/")
        com.nielsen.confirmit.webservices.surveydata.UpdateRespondentsWithCatiScheduling.Ds ds,
        @WebParam(name = "validate", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/")
        boolean validate,
        @WebParam(name = "merge", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/")
        boolean merge,
        @WebParam(name = "uniqueKey", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/")
        java.lang.String uniqueKey,
        @WebParam(name = "inTransaction", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/")
        boolean inTransaction,
        @WebParam(name = "transactionKey", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/")
        int transactionKey,
        @WebParam(name = "schedulingMode", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/")
        com.nielsen.confirmit.webservices.surveydata.CatiScheduling schedulingMode
    );

    @WebMethod(operationName = "DeleteData", action = "http://firmglobal.com/Confirmit/webservices/8.5/DeleteData")
    @RequestWrapper(localName = "DeleteData", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/", className = "com.nielsen.confirmit.webservices.surveydata.DeleteData")
    @ResponseWrapper(localName = "DeleteDataResponse", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/", className = "com.nielsen.confirmit.webservices.surveydata.DeleteDataResponse")
    @WebResult(name = "DeleteDataResult", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/")
    public int deleteData(

        @WebParam(name = "key", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/")
        java.lang.String key,
        @WebParam(name = "transferDef", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/")
        com.nielsen.confirmit.webservices.surveydata.TransferDef transferDef
    );

    @WebMethod(operationName = "GetRespondentEmailLogByTaskGeneral", action = "http://firmglobal.com/Confirmit/webservices/8.5/GetRespondentEmailLogByTaskGeneral")
    @RequestWrapper(localName = "GetRespondentEmailLogByTaskGeneral", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/", className = "com.nielsen.confirmit.webservices.surveydata.GetRespondentEmailLogByTaskGeneral")
    @ResponseWrapper(localName = "GetRespondentEmailLogByTaskGeneralResponse", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/", className = "com.nielsen.confirmit.webservices.surveydata.GetRespondentEmailLogByTaskGeneralResponse")
    @WebResult(name = "GetRespondentEmailLogByTaskGeneralResult", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/")
    public com.nielsen.confirmit.webservices.surveydata.ConfirmitData getRespondentEmailLogByTaskGeneral(

        @WebParam(name = "key", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/")
        java.lang.String key,
        @WebParam(name = "projectId", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/")
        java.lang.String projectId,
        @WebParam(name = "fieldNames", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/")
        com.nielsen.confirmit.webservices.surveydata.ArrayOfString1 fieldNames,
        @WebParam(name = "taskId", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/")
        long taskId
    );

    @WebMethod(operationName = "GetRespondentsGeneral", action = "http://firmglobal.com/Confirmit/webservices/8.5/GetRespondentsGeneral")
    @RequestWrapper(localName = "GetRespondentsGeneral", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/", className = "com.nielsen.confirmit.webservices.surveydata.GetRespondentsGeneral")
    @ResponseWrapper(localName = "GetRespondentsGeneralResponse", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/", className = "com.nielsen.confirmit.webservices.surveydata.GetRespondentsGeneralResponse")
    @WebResult(name = "GetRespondentsGeneralResult", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/")
    public com.nielsen.confirmit.webservices.surveydata.ConfirmitData getRespondentsGeneral(

        @WebParam(name = "key", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/")
        java.lang.String key,
        @WebParam(name = "respondentTransferDef", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/")
        com.nielsen.confirmit.webservices.surveydata.RespondentTransferDef respondentTransferDef
    );

    @WebMethod(operationName = "UpdateRespondents", action = "http://firmglobal.com/Confirmit/webservices/8.5/UpdateRespondents")
    @RequestWrapper(localName = "UpdateRespondents", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/", className = "com.nielsen.confirmit.webservices.surveydata.UpdateRespondents")
    @ResponseWrapper(localName = "UpdateRespondentsResponse", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/", className = "com.nielsen.confirmit.webservices.surveydata.UpdateRespondentsResponse")
    @WebResult(name = "UpdateRespondentsResult", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/")
    public com.nielsen.confirmit.webservices.surveydata.ArrayOfErrorMessage updateRespondents(

        @WebParam(name = "key", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/")
        java.lang.String key,
        @WebParam(name = "projectId", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/")
        java.lang.String projectId,
        @WebParam(name = "ds", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/")
        com.nielsen.confirmit.webservices.surveydata.UpdateRespondents.Ds ds,
        @WebParam(name = "validate", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/")
        boolean validate,
        @WebParam(name = "merge", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/")
        boolean merge,
        @WebParam(name = "uniqueKey", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/")
        java.lang.String uniqueKey,
        @WebParam(name = "inTransaction", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/")
        boolean inTransaction,
        @WebParam(name = "transactionKey", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/")
        int transactionKey
    );

    @WebMethod(operationName = "ExecuteQuery", action = "http://firmglobal.com/Confirmit/webservices/8.5/ExecuteQuery")
    @RequestWrapper(localName = "ExecuteQuery", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/", className = "com.nielsen.confirmit.webservices.surveydata.ExecuteQuery")
    @ResponseWrapper(localName = "ExecuteQueryResponse", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/", className = "com.nielsen.confirmit.webservices.surveydata.ExecuteQueryResponse")
    @WebResult(name = "ExecuteQueryResult", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/")
    public com.nielsen.confirmit.webservices.surveydata.ExecuteQueryResponse.ExecuteQueryResult executeQuery(

        @WebParam(name = "key", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/")
        java.lang.String key,
        @WebParam(name = "query", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/")
        com.nielsen.confirmit.webservices.surveydata.SurveyQuery query
    );

    @WebMethod(operationName = "ExecuteQueryGeneral", action = "http://firmglobal.com/Confirmit/webservices/8.5/ExecuteQueryGeneral")
    @RequestWrapper(localName = "ExecuteQueryGeneral", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/", className = "com.nielsen.confirmit.webservices.surveydata.ExecuteQueryGeneral")
    @ResponseWrapper(localName = "ExecuteQueryGeneralResponse", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/", className = "com.nielsen.confirmit.webservices.surveydata.ExecuteQueryGeneralResponse")
    @WebResult(name = "ExecuteQueryGeneralResult", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/")
    public com.nielsen.confirmit.webservices.surveydata.ConfirmitData executeQueryGeneral(

        @WebParam(name = "key", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/")
        java.lang.String key,
        @WebParam(name = "query", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/")
        com.nielsen.confirmit.webservices.surveydata.SurveyQuery query
    );

    @WebMethod(operationName = "GetData", action = "http://firmglobal.com/Confirmit/webservices/8.5/GetData")
    @RequestWrapper(localName = "GetData", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/", className = "com.nielsen.confirmit.webservices.surveydata.GetData")
    @ResponseWrapper(localName = "GetDataResponse", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/", className = "com.nielsen.confirmit.webservices.surveydata.GetDataResponse")
    @WebResult(name = "GetDataResult", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/")
    public com.nielsen.confirmit.webservices.surveydata.TransferResult getData(

        @WebParam(name = "key", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/")
        java.lang.String key,
        @WebParam(name = "transferDef", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/")
        com.nielsen.confirmit.webservices.surveydata.TransferDefBase transferDef,
        @WebParam(name = "token", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/")
        com.nielsen.confirmit.webservices.surveydata.ResponseToken token
    );

    @WebMethod(operationName = "SetRespondentUniqueKey", action = "http://firmglobal.com/Confirmit/webservices/8.5/SetRespondentUniqueKey")
    @RequestWrapper(localName = "SetRespondentUniqueKey", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/", className = "com.nielsen.confirmit.webservices.surveydata.SetRespondentUniqueKey")
    @ResponseWrapper(localName = "SetRespondentUniqueKeyResponse", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/", className = "com.nielsen.confirmit.webservices.surveydata.SetRespondentUniqueKeyResponse")
    public void setRespondentUniqueKey(

        @WebParam(name = "key", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/")
        java.lang.String key,
        @WebParam(name = "projectId", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/")
        java.lang.String projectId,
        @WebParam(name = "uniqueKey", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/")
        java.lang.String uniqueKey
    );

    @WebMethod(operationName = "UpdateDataGeneral", action = "http://firmglobal.com/Confirmit/webservices/8.5/UpdateDataGeneral")
    @RequestWrapper(localName = "UpdateDataGeneral", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/", className = "com.nielsen.confirmit.webservices.surveydata.UpdateDataGeneral")
    @ResponseWrapper(localName = "UpdateDataGeneralResponse", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/", className = "com.nielsen.confirmit.webservices.surveydata.UpdateDataGeneralResponse")
    @WebResult(name = "UpdateDataGeneralResult", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/")
    public com.nielsen.confirmit.webservices.surveydata.ArrayOfErrorMessage updateDataGeneral(

        @WebParam(name = "key", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/")
        java.lang.String key,
        @WebParam(name = "transferDef", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/")
        com.nielsen.confirmit.webservices.surveydata.TransferDef transferDef,
        @WebParam(name = "data", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/")
        com.nielsen.confirmit.webservices.surveydata.ConfirmitData data,
        @WebParam(name = "applyRules", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/")
        boolean applyRules,
        @WebParam(name = "inTransaction", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/")
        boolean inTransaction,
        @WebParam(name = "transactionKey", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/")
        int transactionKey
    );

    @WebMethod(operationName = "GetRespondentsTokenizedGeneral", action = "http://firmglobal.com/Confirmit/webservices/8.5/GetRespondentsTokenizedGeneral")
    @RequestWrapper(localName = "GetRespondentsTokenizedGeneral", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/", className = "com.nielsen.confirmit.webservices.surveydata.GetRespondentsTokenizedGeneral")
    @ResponseWrapper(localName = "GetRespondentsTokenizedGeneralResponse", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/", className = "com.nielsen.confirmit.webservices.surveydata.GetRespondentsTokenizedGeneralResponse")
    @WebResult(name = "GetRespondentsTokenizedGeneralResult", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/")
    public com.nielsen.confirmit.webservices.surveydata.RespondentConfirmitDataResult getRespondentsTokenizedGeneral(

        @WebParam(name = "key", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/")
        java.lang.String key,
        @WebParam(name = "respondentTransferDef", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/")
        com.nielsen.confirmit.webservices.surveydata.RespondentTransferDef respondentTransferDef,
        @WebParam(name = "token", targetNamespace = "http://firmglobal.com/Confirmit/webservices/8.5/")
        com.nielsen.confirmit.webservices.surveydata.RespondentToken token
    );
}
